name: Linting

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'

    - name: Install linting tools
      run: make install-tools

    - name: Run linting
      run: make lt
