name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.5'

    - name: Install test tools
      run: make install-test-tools

    - name: Run tests
      run: make test
